/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/L0EzHutRp8h
 */
import { CardContent, Card } from "@/components/ui/card"

export function carddetail() {
  return (
    (<Card>
      <CardContent className="p-6">
        <div className="grid gap-4">
          <img
            alt="Product Image"
            className="aspect-square object-cover rounded-lg overflow-hidden border border-gray-200 dark:border-gray-800 dark:border-gray-800"
            height={400}
            src="/placeholder.svg"
            width={400} />
          <div className="grid gap-2">
            <h2 className="text-2xl font-bold">Acme Prism T-Shirt: The Cozy Chromatic Blend</h2>
            <p className="text-2xl font-bold">$99</p>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-0.5">
                <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
                <StarIcon
                  className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
                <StarIcon
                  className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
              </div>
            </div>
          </div>
          <div className="grid gap-4 text-sm leading-loose">
            <p>
              Introducing the Acme Prism T-Shirt, a perfect blend of style and comfort for the modern individual. This
              tee is crafted with a meticulous composition of 60% combed ringspun cotton and 40% polyester jersey,
              ensuring a soft and breathable fabric that feels gentle against the skin.
            </p>
            <p>
              The design of the Acme Prism T-Shirt is as striking as it is comfortable. The shirt features a unique
              prism-inspired pattern that adds a modern and eye-catching touch to your ensemble.
            </p>
          </div>
        </div>
      </CardContent>
    </Card>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}
