/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IZh3p1PjNgD
 */
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function dashboard() {
  return (
    (<div
      className="flex min-h-screen items-start p-4 md:items-center md:p-6 lg:p-8">
      <div className="grid gap-4 w-full max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold">Products</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Manage your products here. You can add, edit, or delete products as you wish.
        </p>
        <div className="grid gap-4 md:gap-6">
          <Card>
            <CardContent className="flex items-center gap-4 p-4 md:p-6">
              <img
                alt="Product image"
                className="aspect-square rounded-md object-cover border"
                height="150"
                src="/placeholder.svg"
                width="150" />
              <div className="grid gap-1 text-sm md:grid-cols-2 md:text-base">
                <div className="font-bold">Glimmer Lamps</div>
                <div>Beautifully designed lamps that add a touch of elegance to your home.</div>
                <div className="font-bold">$49.99</div>
                <div>Available for Order</div>
              </div>
            </CardContent>
            <CardFooter className="flex gap-2 p-4 md:p-6">
              <Button size="sm">Edit</Button>
              <Button size="sm">Delete</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardContent className="flex items-center gap-4 p-4 md:p-6">
              <img
                alt="Product image"
                className="aspect-square rounded-md object-cover border"
                height="150"
                src="/placeholder.svg"
                width="150" />
              <div className="grid gap-1 text-sm md:grid-cols-2 md:text-base">
                <div className="font-bold">Aqua Filters</div>
                <div>Keep your water clean and pure with our advanced filtration system.</div>
                <div className="font-bold">$19.99</div>
                <div>In Stock</div>
              </div>
            </CardContent>
            <CardFooter className="flex gap-2 p-4 md:p-6">
              <Button size="sm">Edit</Button>
              <Button size="sm">Delete</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardContent className="flex items-center gap-4 p-4 md:p-6">
              <img
                alt="Product image"
                className="aspect-square rounded-md object-cover border"
                height="150"
                src="/placeholder.svg"
                width="150" />
              <div className="grid gap-1 text-sm md:grid-cols-2 md:text-base">
                <div className="font-bold">Eco Planters</div>
                <div>Stylish and eco-friendly planters for your indoor and outdoor greenery.</div>
                <div className="font-bold">$29.99</div>
                <div>Backordered</div>
              </div>
            </CardContent>
            <CardFooter className="flex gap-2 p-4 md:p-6">
              <Button size="sm">Edit</Button>
              <Button size="sm">Delete</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>)
  );
}
