/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7uOJe7TqRA1
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function login() {
  return (
    (<div className="flex flex-col items-center space-y-4">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Welcome</h1>
        <p className="text-sm font-medium leading-none">Enter your email below to login to your account</p>
      </div>
      <div className="w-[400px] space-y-4">
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="m@example.com" required type="email" />
        </div>
        <div className="space-y-2">
          <div className="flex items-center">
            <Label htmlFor="password">Password</Label>
            <Link className="ml-auto inline-block text-sm underline" href="#">
              Forgot your password?
            </Link>
          </div>
          <Input id="password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Login
        </Button>
        <Button className="w-full">Enter as Guest</Button>
      </div>
    </div>)
  );
}
